apiVersion: v1

kind: ReplicationController

metadata:
  name: hello-rc

spec:
  replicas: 3
  selector:
    app: hello-pod-rc
  template:
    metadata:
      name: hello-pod-rc
      labels:
        app: hello-pod-rc
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
