apiVersion: v1

kind: Service

metadata:
  name: hello-service-app
  labels:
    app: helloService
    type: plugins

spec:
  type: NodePort
  selector:
    app: hello-dapp
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30009
