apiVersion: v1

kind: Service

metadata:
  name: hello-service
  labels:
    app: helloService
    type: plugins

spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    type: plugins
    app: hello