apiVersion: v1

kind: Pod

metadata:
  name: hello-pod
  labels:
    app: hello
    type: plugins

spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80

